[package]

name = "rustybot"
version = "1.0.0"
authors = [ "Jfreegman <Jfreegman@gmail.com>" ]

[dependencies]
lazy_static = "1.3.0"
time = "0.1.42"
rand = "0.6.5"
byteorder = "1.3.2"
ctrlc = "3.1.3"

[dependencies.rstox]
git = "https://github.com/suhr/rstox.git"

[profile.dev]
debug = true
